common/models/User.php
<?php

namespace common\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

/**
 * User model
 *
 * @property integer $id
 * @property string $username
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $verification_token
 * @property string $email
 * @property string $fio
 * @property int $role
 * @property string $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $password write-only password
 */
class User extends ActiveRecord implements IdentityInterface
{

    const SCENARIO_REGISTER = 'register';

    const STATUS_DELETED = 0;
    const STATUS_INACTIVE = 9;
    const STATUS_ACTIVE = 10;

    const ROLE_ADMIN = 10;
    const ROLE_USER = 9;

    public $password;

    public $objects_arr;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            ['username', 'unique', 'targetClass' => '\common\models\User', 'message' => 'Этот логин уже занят!'],
            ['username', 'string', 'min' => 2, 'max' => 255],
            [['password'],'required','on' => self::SCENARIO_REGISTER],
            ['password', 'string', 'min' => Yii::$app->params['user.passwordMinLength']],
            ['objects_arr','safe'],
            [['fio','username'],'required'],
            [['fio'],'string'],
            ['fio', 'string'],
            ['role', 'default', 'value' => self::ROLE_USER],
            ['role', 'in', 'range' => [self::ROLE_ADMIN, self::ROLE_USER]],
            ['status', 'default', 'value' => self::STATUS_INACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_INACTIVE, self::STATUS_DELETED]],
        ];
    }

    public function attributeLabels()
    {
        return [
            'fio' => 'ФИО',
            'role' => 'Роль',
            'status' => 'Статус',
            'username'=>'Логин',
            'password'=>'Пароль',
            'created_at' => 'Создано',
            'updated_at' => 'Обновлено',
        ];
    }


    public function getUsername()
    {

        if ($this->fio) {
            return $this->fio;
        }
        return $this->username;
    }

    public function afterFind()
    {
        $this->objects_arr = $this->objects;
        parent::afterFind(); // TODO: Change the autogenerated stub
    }


    public function getObjects()
    {
        return $this->hasMany(Objects::className(), ['id' => 'object_id'])
            ->viaTable('users_objects', ['user_id' => 'id']);
    }

    public function saveObjects($objects)
    {
        if (is_array($objects))
        {
            $this->clearCurrentPlaylists();

            foreach($objects as $objects_id)
            {
                $object = Objects::findOne($objects_id);
                $this->link('objects', $object);
            }
        }
    }

    public function clearCurrentPlaylists()
    {
        UsersObjects::deleteAll(['user_id'=>$this->id]);
    }

    public function afterSave($insert, $changedAttributes)
    {
        $this->saveObjects($this->objects_arr);
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }


    /**
     * {@inheritdoc}
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds user by verification email token
     *
     * @param string $token verify email token
     * @return static|null
     */
    public static function findByVerificationToken($token)
    {
        return static::findOne([
            'verification_token' => $token,
            'status' => self::STATUS_INACTIVE
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return bool
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int)substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }

    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * {@inheritdoc}
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * {@inheritdoc}
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Generates new token for email verification
     */
    public function generateEmailVerificationToken()
    {
        $this->verification_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }
}

backend/controllers/ObjectsController.php
<?php

namespace backend\controllers;

use common\models\Objects;
use common\models\search\ObjectsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ObjectsController implements the CRUD actions for Objects model.
 */
class ObjectsController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Objects models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new ObjectsSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);
        $dataProvider->pagination->pageSize=100;

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Objects model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Objects model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Objects();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Objects model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Objects model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Objects model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Objects the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Objects::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/controllers/UserController.php
<?php

namespace backend\controllers;

use common\models\User;
use common\models\search\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param int $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();
        $model->scenario=User::SCENARIO_REGISTER;
        if ($this->request->isPost) {
            if ($model->load($this->request->post())) {

                $model->email = $model->username.'@mail.ru';
                $model->setPassword($model->password);
                $model->generateAuthKey();
                $model->generateEmailVerificationToken();
                 $model->save();
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post())) {
            if($model->password) {
                $model->setPassword($model->password);
            }
            $model->save();
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model common\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">

    <?php $form = ActiveForm::begin(['options' => ['autocomplete' => 'off']]); ?>

    <div class="row">
        <div class="col-md-4">
            <?= $form->field($model, 'username')->textInput() ?>
        </div>
        <div class="col-md-4">
            <?php if ($model->isNewRecord) { ?>
                <?= $form->field($model, 'password')->passwordInput() ?>
            <?php } else { ?>
                <?= $form->field($model, 'password')->textInput()->label('Новый пароль') ?>
            <?php } ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'fio')->textInput(['maxlength' => true]) ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <?=$form->field($model, 'role')->dropDownList([
               \common\models\User::ROLE_USER => 'Пользователь',
                \common\models\User::ROLE_ADMIN => 'Администратор',
            ]);?>
        </div>
        <div class="col-md-4">
            <?=$form->field($model, 'status')->dropDownList([
                \common\models\User::STATUS_ACTIVE=> 'Активен',
                \common\models\User::STATUS_INACTIVE => 'Не активен',
            ]);?>
        </div>
    </div>

    <hr>
    <br>
    <h3 class="text-center">Объекты для пользователя</h3>

    <div class="row">

        <div class="col-md-12">
            <?php

            $data = \common\models\Objects::find()->andWhere(['status' => 1])->all();
            $data = ArrayHelper::map($data, 'id', 'name');
            ?>
            <?= $form->field($model, 'objects_arr')->widget(Select2::classname(), [
                'data' => $data,
                'options' => ['placeholder' => 'Выберите объекты ...', 'multiple' => true],
                'pluginOptions' => [
                    'tags' => true,
                    'tokenSeparators' => [',', ' '],
                    'allowClear' => true,
                    'maximumInputLength' => 1000
                ],
            ])->label('Объекты'); ?>

        </div>
    </div>
    </div>


    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\search\UserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'auth_key') ?>

    <?= $form->field($model, 'password_hash') ?>

    <?= $form->field($model, 'password_reset_token') ?>

    <?php // echo $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'verification_token') ?>

    <?php // echo $form->field($model, 'fio') ?>

    <?php // echo $form->field($model, 'phone') ?>

    <?php // echo $form->field($model, 'role') ?>

    <?php // echo $form->field($model, 'id_partner') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/user/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = 'Новый пользователь';
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>


    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

backend/views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = 'Редактирование пользователя: ' . $model->getUsername();
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->getUsername(), 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Редактирование';
?>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

backend/views/user/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use tecnocen\yearcalendar\widgets\Calendar;
use yii\web\JsExpression;
use yii\db\Expression;
use nepster\basis\helpers\DateTimeHelper;

/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = $model->getUsername();
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>


    <p>
        <?= Html::a('Редактировать', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вы точно хотите удалить данного пользователя?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

<div class="row">
    <div class="col-md-6">
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'username',
            [
                'attribute'=>'fio',
            ],
            //'auth_key',
            //'password_hash',
            //'password_reset_token',
//            'email:email',
            [
                'attribute' => 'role',
                'label'=>'Роль',
                'format'=>'html',
                'value'=>function($data)
                {
                    if($data->role == \common\models\User::ROLE_ADMIN)
                    {
                        return '<div class="badge badge-success">Администратор</div>';
                    }

                    if($data->role ==\common\models\User::ROLE_USER)
                    {
                        return '<div class="badge badge-warning">Пользователь</div>';
                    }
                }
            ],
            [
                'attribute' => 'status',
                'format'=>'html',
                'value'=>function($data)
                {
                    if($data->status == \common\models\User::STATUS_ACTIVE)
                    {

                        return '<div class="badge badge-success">Активен</div>';
                    }

                    if($data->status == \common\models\User::STATUS_INACTIVE)
                    {
                        return '<div class="badge badge-danger">Не активен</div>';
                    }
                }
            ],
            'created_at:datetime',
            'updated_at:datetime',

        ],
    ]) ?>
    </div>


    <style>

        div.zabuto_calendar .table tr td.event div.day{

            background-color: #57B657;
            color: white;
        }

    </style>
    <div class="col-md-6">
        <?php if($model->getObjects()->all()) {?>
                    <h2 >Объекты для этого пользователя</h2>
                    <hr>
                    <?php
                    $objects=$model->getObjects();
                    ?>

                    <?php foreach( $objects->all() as $item) { ?>
                        <h4><a href="<?=\yii\helpers\Url::to(['/objects/view','id'=>$item->id])?>"><?=$item->name?></h4></a>
                    <?php } ?>
        <?php }?>
    </div>
</div>
<hr>

<?php

$records = \common\models\Records::find()->andWhere(['user_id'=>$model->getId()])->orderBy('id desc')->all();

$datesArrived1 = \yii\helpers\ArrayHelper::getColumn($records,'arrived');

$datesArrived = array_map(function ($item) {
    return date('d.m.Y',$item);
}, $datesArrived1);


$dateList = [];
foreach ($records as $item){
    $dateList[date('Y-m-d', $item->arrived)]['date'] =  date('Y,n-1,j', $item->arrived);
    $dateFormat = date('Y-m-d', $item->arrived);

    $events = \common\models\Records::find()->andWhere(['user_id'=>$model->getId()])->andWhere(['date_format'=>date('d.m.Y', $item->arrived)]);

    $dateList[date('Y-m-d', $item->arrived)]['count'] = $events->count();
    $objects = \yii\helpers\ArrayHelper::getColumn($events->all(),'object');

    $str = '';

    foreach ($events->all() as $items){
        if($items->departed) {
            $time = DateTimeHelper::diffFullPeriod($items->arrived, $items->departed);
            $str = $str.'<li>'.$items->object.' (Время на объекте: '.$time.')</li>';
        }else {
            $arrived = date('d.m.Y', $items->arrived);
            $str = $str.'<li>'.$items->object.' (Прибытие'.$arrived.')</li>';
        }
    }


    $dateList[date('Y-m-d', $item->arrived)]['text'] =
        '<span><b>'.Yii::$app->formatter->asDate(date('Y-M-d', $item->arrived)).'</b><br></span>'.
        '<span><b>Прибытий на объекты: </b>('.$events->count().')</span>'.$str
    ;
}


?>


<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<br>
<div id="calendar_basic" style="width: 100%; height: 300px;"></div>

<script type="text/javascript">
    google.charts.load("current", {packages: ["calendar"], language: 'ru'});
    google.charts.setOnLoadCallback(drawChart);
    function drawChart() {
        var dataTable = new google.visualization.DataTable();
        dataTable.addColumn({type: 'date', id: 'Date'});
        dataTable.addColumn({type: 'number', id: 'Won/Loss'});
        dataTable.addColumn({type: 'string', 'role': 'tooltip', 'p': {'html': true} });


        dataTable.addRows([

            <?php foreach ($dateList as $date) { ?>
            [new Date(<?=$date['date']?>), <?=$date['count']?>,'<div style="min-width:350px;padding: 5px; color: #0b2e13; font-size: 14px"><?=$date['text']?></div>'],
          <?php } ?>
        ]);

        var chart = new google.visualization.Calendar(document.getElementById('calendar_basic'));

        var options = {
            title: "График посещений",
            height: 300,
            tooltip: {isHtml: true},
            trigger: 'both',
            colorAxis: {minValue: 0, maxValue: <?=$model->getObjects()->count()?>, colors: ['#FF0000', '#00FF00']},
            calendar: {

                focusedCellColor: {
                    stroke: 'red',
                    strokeOpacity: 0.8,
                    strokeWidth: 3
                },
                cellSize: 20,
            },

            noDataPattern: {
                backgroundColor: '#FF0000',
                color: '#fff'
            }

        };
        chart.draw(dataTable, options);
    }

</script>

backend/views/user/view1.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use tecnocen\yearcalendar\widgets\Calendar;
use yii\web\JsExpression;


/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = $model->getUsername();
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>


    <p>
        <?= Html::a('Редактировать', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вы точно хотите удалить данного пользователя?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

<div class="row">
    <div class="col-md-6">
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'username',
            [
                'attribute'=>'fio',
            ],
            //'auth_key',
            //'password_hash',
            //'password_reset_token',
//            'email:email',
            [
                'attribute' => 'role',
                'label'=>'Роль',
                'format'=>'html',
                'value'=>function($data)
                {
                    if($data->role == \common\models\User::ROLE_ADMIN)
                    {
                        return '<div class="badge badge-success">Администратор</div>';
                    }

                    if($data->role ==\common\models\User::ROLE_USER)
                    {
                        return '<div class="badge badge-warning">Пользователь</div>';
                    }
                }
            ],
            [
                'attribute' => 'status',
                'format'=>'html',
                'value'=>function($data)
                {
                    if($data->status == \common\models\User::STATUS_ACTIVE)
                    {

                        return '<div class="badge badge-success">Активен</div>';
                    }

                    if($data->status == \common\models\User::STATUS_INACTIVE)
                    {
                        return '<div class="badge badge-danger">Не активен</div>';
                    }
                }
            ],
            'created_at:datetime',
            'updated_at:datetime',

        ],
    ]) ?>
    </div>


    <style>

        div.zabuto_calendar .table tr td.event div.day{

            background-color: #57B657;
            color: white;
        }

    </style>
    <div class="col-md-6">
        <?php if($model->getObjects()->all()) {?>
                    <h2 >Объекты для этого пользователя</h2>
                    <hr>
                    <?php
                    $objects=$model->getObjects();
                    ?>

                    <?php foreach( $objects->all() as $item) { ?>
                        <h4><a href="<?=\yii\helpers\Url::to(['/objects/view','id'=>$item->id])?>"><?=$item->name?></h4></a>
                    <?php } ?>
        <?php }?>
    </div>
</div>
<hr>

<?php

$records = \common\models\Records::find()->andWhere(['user_id'=>$model->getId()])->orderBy('id desc')->all();

$dateList = [];
foreach ($records as $item){
    $dateFormat = date('Y-m-d', $item->arrived);

    $countEvents = \common\models\Records::find()->andWhere(['user_id'=>$model->getId()])->andWhere(['date_format'=>date('d.m.Y', $item->arrived)])->count();

    $dateList[]=['title'=>'Количество событий: '.$countEvents,'date'=>$dateFormat,"badge"=>false];
}


?>
<script
        src="https://code.jquery.com/jquery-3.6.0.js"
        integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
        crossorigin="anonymous"></script>

<script>
    var eventData = <?php echo json_encode($dateList) ?>;
    $(document).ready(function () {
        $(".calendar").zabuto_calendar({
            cell_border: true,
            today: true,
            language: "ru",
            data: eventData,
            show_days: true,
            weekstartson: 1,
            nav_icon: {
                prev: '<i class="icon-arrow-left"></i>',
                next: '<i class="icon-arrow-right"></i>'
            },
            action: function() {
                if (this.className.indexOf('event') > -1) {
                    loadDay(this.id);
                    $('.calendarEventsModalTitle').html("");
                    $('.calendarEventsModalBody').html("");
                }
            }
        });

        function loadDay(id) {
            id = id.substring(id.length - 10, id.length);
            id = (new Date(id)).toLocaleDateString();
            var user_id = <?=$model->getId()?>;
            $.ajax({
                url: '/backend/calendar/events',
                cache: false,
                data: { id: id, user_id: user_id, },
                type: "get",
                success: function (data) {
                    $('div.desc-events .title').html("События на " + id);
                    $('div.desc-events').show();
                    $('div.desc-events .body').html(data);
                    $('div#loading').hide();
                },
                error: function (data) {
                    console.log(data);
                }
            });
        };
    });
</script>
<br><br>

<!--<div class="container-fluid">-->
<!--<div class="row">-->
<!--    <h3 class="text-center" style="margin-left: 25px ">График событий</h3><br><BR>-->
<!--    <div class="col-lg-8">-->
<!--        <div class="calendar">-->
<!--            <div class="desc-events" style="display:none;background-color: aliceblue;padding: 20px;border-radius: 10px;">-->
<!--                <br>-->
<!--                <h4 class="title" style="font-size: 17px"></h4>-->
<!--                <br>-->
<!--                <div class="body" style="font-size: 16px;">-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!---->
<!--    </div>-->
<!--</div>-->
<!---->
<!--</div>-->